name: IslandPortal
version: '${version}'
main: net.danh.islandportal.IslandPortal
api-version: '26.1.2'
load: POSTWORLD
folia-supported: true
authors: [ VoChiDanh ]
dependencies:
  server:
    BentoBox:
      load: AFTER
      required: false
    SuperiorSkyblock2:
      load: AFTER
      required: false
    Skyllia:
      load: AFTER
      required: false
    Vault:
      load: AFTER
      required: false
    ShopGUIPlus:
      load: AFTER
      required: false
    Essentials:
      load: AFTER
      required: false
    CMI:
      load: AFTER
      required: false
    HeadDatabase:
      load: AFTER
      required: false
    ItemsAdder:
      load: AFTER
      required: false
    Oraxen:
      load: AFTER
      required: false
    Nexo:
      load: AFTER
      required: false
    MMOItems:
      load: AFTER
      required: false
    MythicMobs:
      load: AFTER
      required: false
    packetevents:
      load: AFTER
      required: false
    WorldEdit:
      load: AFTER
      required: false
    FastAsyncWorldEdit:
      load: AFTER
      required: false
permissions:
  islandportal.admin:
    default: op
